### ISSUE TITLE
Bug that needs to be fixed in Apollo

### ISSUE THREAD

**Issue by kiwiplusapp** [kiwiplusapp/kiwi-app#1]
Github Community help me fix this error :)

ERROR Error: Uncaught (in promise): ApolloError: ER_BAD_FIELD_ERROR: Unknown column `'request.reviewId'` in 'field list'

**Comment by kiwiplusapp** [comment]
### Error Fixed 

Summary: `reviewId` table does not exist in mysql database.

**Step 1** Login to the MySQL docker image:` docker exec -it <docker-mysql image-id-here> mysql -u root` use this passwd: `defaultpassword`

**Step 2** Create a new colum in the DB `USE ridy;` & then `ALTER TABLE request ADD COLUMN reviewId INT;`

**Comment by YonasAlem** [comment]
I was trying to clone the repo and set up it locally but it has been very difficult.

**Comment by kiwiplusapp** [comment]
Hello, sorry for the delay, its more difficult to run the backend locally, please contact me on whatsapp +543446202908 if you have a server with ubuntu 18.04+ I can help you :)
